name: Build and Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-driver:
    name: SSD_Driver Tests
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      run: nuget restore SSD_Driver/SSD_Driver.sln

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build SSD_Driver.sln
      run: msbuild SSD_Driver/SSD_Driver.sln /p:Configuration=Debug /p:Platform=x64

    - name: Run SSD_DriverTests
      run: SSD_Driver\x64\Debug\SSD_Driver.exe --gtest_output=xml:test-results-driver.xml

  test-shell:
    name: SSD_TestShell Tests
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      run: nuget restore SSD_TestShell/SSD_TestShell.sln

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build SSD_TestShell.sln
      run: msbuild SSD_TestShell/SSD_TestShell.sln /p:Configuration=Debug /p:Platform=x64

    - name: Copy shell_script.txt to output directory
      shell: cmd
      run: copy SSD_TestShell\shell_script.txt .

    - name: Run SSD_TestShellTests
      run: SSD_TestShell\x64\Debug\SSD_TestShell.exe --gtest_output=xml:test-results-shell.xml

